apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Chart.Name}}-deployment-{{.Values.environment}}
 labels:
  app: {{.Chart.Name}}-deployment-{{.Values.environment}}

spec:
  selector:
    matchLabels:
      app: {{.Chart.Name}}-deployment-{{.Values.environment}}

  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-deployment-{{.Values.environment}}
      annotations: # This checksum will change whenever the ConfigMap changes 
        checksum/common-config: {{ include (print $.Template.BasePath "/common-config.yaml") . | sha256sum }} 
        checksum/env-config: {{ include (print $.Template.BasePath (printf "/%s-config.yaml" .Values.environment)) . | sha256sum }}

    spec:
     containers:
       - name : {{.Chart.Name}}-{{.Values.pod.containerName}}-{{.Values.environment}}
         image: {{.Values.pod.imageName}}
         ports:
          - containerPort : {{.Values.pod.containerPort}} #this should match the port nginx listening on
         volumeMounts:
         - name: {{.Values.config.volume}}
           mountPath: /{{.Values.config.mountPath}}
           readOnly: true
        #  - name: common-{{.Values.config.volume}}
        #    mountPath: /{{.Values.config.mountPath}}
        #    readOnly: true
         env:
           - name: nginxPort
             valueFrom:
               configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: common-{{.Values.config.name}}
              # Specify the key associated with the value
                  key: nginxPort
           - name: appName
             valueFrom:
               configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: common-{{.Values.config.name}}
              # Specify the key associated with the value
                  key: appName
           - name: env
             valueFrom:
               configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: {{.Values.environment}}-{{.Values.config.name}}
              # Specify the key associated with the value
                  key: env
     volumes:
     - name: {{.Values.config.volume}}
       configMap:
         name: {{.Values.environment}}-{{.Values.config.name}}
     - name: common-{{.Values.config.volume}}
       configMap:
         name: common-{{.Values.config.name}}

#we are loading all environment variables from the config map with name :dev-app-config


#helm install helm-release helm-test
#helm upgrade helm-release helm-test